version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run publish
workflows:
  "Cloudflare worker deployment":
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - deploy:
          context: cf-context
          filters:
            branches:
              only: master