version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - node/install-packages
      - run: npm run publish
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-context