version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  deploy:
    steps:
      - checkout
      - node/install-packages
      - run: npx wrangler publish
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-context